// <auto-generated />
using System;
using BuildingEnergyCalculator.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuildingEnergyCalculator.Migrations
{
    [DbContext(typeof(EnergyCalculatorDbContext))]
    [Migration("20230403160815_InitialNewBaseBEC")]
    partial class InitialNewBaseBEC
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BuildingEnergyCalculator.Entities.BuildingMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Cw")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DivisionalStructureId")
                        .HasColumnType("int");

                    b.Property<double>("GammaSW")
                        .HasColumnType("float");

                    b.Property<double>("GammaW")
                        .HasColumnType("float");

                    b.Property<double>("LayerThickness")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Ro")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DivisionalStructureId");

                    b.ToTable("BuildingMaterials");
                });

            modelBuilder.Entity("BuildingEnergyCalculator.Entities.DivisionalStructure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DivisionalThickness")
                        .HasColumnType("float");

                    b.Property<double>("R")
                        .HasColumnType("float");

                    b.Property<double>("Rse")
                        .HasColumnType("float");

                    b.Property<double>("Rsi")
                        .HasColumnType("float");

                    b.Property<double>("U")
                        .HasColumnType("float");

                    b.Property<double>("λ")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("DivisionalStructures");
                });

            modelBuilder.Entity("BuildingEnergyCalculator.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BuildingEnergyCalculator.Entities.BuildingMaterial", b =>
                {
                    b.HasOne("BuildingEnergyCalculator.Entities.DivisionalStructure", null)
                        .WithMany("BuildingMaterials")
                        .HasForeignKey("DivisionalStructureId");
                });

            modelBuilder.Entity("BuildingEnergyCalculator.Entities.DivisionalStructure", b =>
                {
                    b.Navigation("BuildingMaterials");
                });
#pragma warning restore 612, 618
        }
    }
}
